language: java

script: ./mvnw clean verify jacoco:report coveralls:report -P buildDockerContainer

jdk:
- oraclejdk8

services:
- docker

before_deploy:
- export JAR_FILE=$(ls target/urlaubsverwaltung-*.jar)
- echo "deploying $JAR_FILE to GitHub releases"
- export RELEASE_NOTES=$(node/node etc/getReleaseNotes.js)
- echo "create release notes $RELEASE_NOTES"

deploy:
- provider: releases
  api_key:
    secure: lEV9X4As9pSBZfJBWIvBzeqfOHGJojQHYYDkKqPb5TKwXjPcsWb/es+JeS6Yqx3hwxjpYL/p4FmczklaVqbABdrMAb+VkU504HwHdKz0qRl2o8Wkf2iCHrDAqTm/UYPPtfMr9RjRBNq8msCB6QChngnj3/C0moh/KUdgiMBPJEw=
  file: "${JAR_FILE}"
  body: "${RELEASE_NOTES}"
  skip_cleanup: true
  on:
    repo: synyx/urlaubsverwaltung
    tags: true
    jdk: oraclejdk8
- provider: script
  skip_cleanup: true
  script: bash etc/deploy_docker_travis.sh
  on:
    repo: synyx/urlaubsverwaltung
    branch: add_docker_image

env:
  global:
  - secure: "m1Lw95blY7v8RURXr79L1w/1ltgGpsGfSsPXJYZ1+UMy9QhBZjgbs/2d9QHEyNhkqh3URgT7YOQ7fXlN8zvDB2FcMFjBAm4fTz9F70UnyJKLkoSNG+5VkWwF56OD80ujnXWpwSsziFj+DluVMv8geFNlLtQxhv7BLx4GcAwX23k="
  - secure: "Wfy6lms6ddTDT5E4kDznw3rhk16s6TU426wjj2/Gvu/ac4D8pMFz9QMuZnvbW07dc7e63e1VB6BFy2dpbkPjyozfsl67CkPdxNb18wYVUIHWaifjOziF00i+FS/17X3YzhvbD0GGl1kDNNKJbbSEAFZJ0gmx0GXdHUyd7QjN1/o="
