language: java

script: ./mvnw verify

after_success:
  - ./mvnw clean verify jacoco:report coveralls:report

jdk:
  - oraclejdk8

deploy:
   provider: script
   script: .travis/release.sh
   skip_cleanup: true
   on:
    repo: synyx/urlaubsverwaltung
    tags: true
    jdk: oraclejdk8
